### ISSUE TITLE
Junit 3/4 special case

### ISSUE THREAD

**Issue by Blackwolf291** [mpkorstanje/surefire-1724-proposal#2]
Quick question, why would junit3 and 4 be a special case here, when the Junit Vintage engine has implemented testcase discovery for them? Would that not eliminate the need for the special case here, by relying on a 3rd engine plugged into junit platform? Not to be nosy but it would make for a cleaner proposal if that works.

**Comment by Blackwolf291** [comment]
TestNG also have a an engine for the platform with discovery implemented, meaning there is an opportunity for a one stop shop here, without special cases on the common test platforms.

**Comment by mpkorstanje** [comment]
I'm the wrong person to task. you'd have to discuss this with Tibor and the other folks that work on Surefire.  But I imagine that they're not looking to break existing support and I can also imagine that the JUnit 5 integration doesn't quite cover all existing cases.
